### ISSUE TITLE
Allow parsing message definitions with unresolved type names

### ISSUE THREAD

**Issue by jhurliman** [foxglove/rosmsg#15]
The `parse()` function only works on "full" message definitions, the type produced by `gendeps --cat` that include multiple message definitions separated by `========` lines and the `MSG:` prefix for non-root types. This library should also support parsing message definitions in the format ROS message definition libraries commonly store them on disk, with one type per file. An additional function to fix up type names after loading all the relevant definitions from disk is probably needed as well.

**Comment by defunctzombie** [comment]
This refers to calling `parse` and giving that a single `.msg` string? I'm guessing that doesn't work today?

**Comment by jhurliman** [comment]
@defunctzombie that's right. It came up when writing a helper tool to convert ROS `.msg` files on disk to parsed message definitions. You have to concatenate a bunch of files together ahead of time, but you don't know which files to concatenate because you haven't parsed anything yet. Another pattern could be a callback that asks you for the `.msg` string whenever it encounters a new type during parsing.
