### ISSUE TITLE
Lazy message field access is dominated by <instance_members_initializer>

### ISSUE THREAD

**Issue by jhurliman** [foxglove/rosmsg#22]
<img width="407" alt="Screen Shot 2021-12-15 at 5 57 50 PM" src="https://user-images.githubusercontent.com/195374/146294095-e886dcbd-fba0-4ab0-818e-9567c016e575.png">

This chart is only really meaningful in context with time spent elsewhere, but I wanted to zoom in far enough to show that a significant portion of Foxglove Studio's 3D rendering loop is spent on the CPU accessing lazy message fields. This may be the same issue as https://githubmemory.com/repo/ChainSafe/ssz/issues/187

**Comment by defunctzombie** [comment]
This is related to https://bugs.chromium.org/p/v8/issues/detail?id=12242&hotlist_id=12935&sort=%20rank%20-ID

Maybe a short-term fix is to not using instance members and do this old-school. Tho I am not sure how instance member initializer is impacted by the getters/setters.

**Comment by defunctzombie** [comment]
Btw you probably meant to open this on https://github.com/foxglove/rosmsg-serialization

**Comment by defunctzombie** [comment]
Fixed by https://github.com/foxglove/rosmsg-serialization/commit/99255811b45ff730bce4c2909bce1e14300fe872
