### ISSUE TITLE
Docmentation for running gendeps2

### ISSUE THREAD

**Issue by huyaoyu** [foxglove/rosmsg#44]
**Description**

Sorry to bother you with this. I think we need simple documentation for people to run `gendeps2` locally, especially for people like me who come from a C++/python background and know nothing about JavaScript/TypeScript.

- Version: Current main branch 1b9df73
- Platform: macOS Sonoma 14.2.1

**Steps To Reproduce**
Just want to use `gendeps2` to generate similar files that are recorded at https://github.com/foxglove/rosmsg-msgs-common/tree/main

I have zero experience with JavaScript/TypeScript and related things. I did everything by quickly googling around. But apparently, I messed up some simple things. The following is what I did.

```bash
cd <a random place>
git clone https://github.com/foxglove/rosmsg.git
cd rosmsg
npm run build
cd ../
npm install ./rosmsg
```

After the above operations, I have `gendeps2` available locally in my terminal. But when I do

```bash
gendeps2
```

I got the following error

```
node:internal/modules/cjs/loader:1146
  throw err;
  ^

Error: Cannot find module '../dist/gendeps2'
Require stack:
- /Users/yaoyuh/Projects/foxglove_packages/rosmsg/bin/gendeps2
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Module.require (node:internal/modules/cjs/loader:1234:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/yaoyuh/Projects/foxglove_packages/rosmsg/bin/gendeps2:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1375:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/yaoyuh/Projects/foxglove_packages/rosmsg/bin/gendeps2' ]
}
```

I checked the source folder and there is a `dist` folder with the content of

```
buildRos2Type.d.ts
buildRos2Type.d.ts.map
gendeps2.d.ts
gendeps2.d.ts.map
index.d.ts
index.d.ts.map
index.js
index.js.map
md5.d.ts
md5.d.ts.map
parse.d.ts
parse.d.ts.map
stringify.d.ts
stringify.d.ts.map
```

**Expected Behavior**

I think I have done something stupid but I cannot tell by myself. However, what I'm expecting to see is the terminal complains like

```
"Usage: gendeps <msgdefs-dir> <msg-file>"
```

as designed at https://github.com/foxglove/rosmsg/blob/1b9df73daf05cae581c78ffb74ceb8772c82282a/src/gendeps2.ts#L14

My final goal is to use `gendeps2` to generate `.msg` files that look like those recorded in [foxglove/rosmsg-msgs-common](https://github.com/foxglove/rosmsg-msgs-common/tree/main), where a single `.msg` file contains all the content of its dependent messages.

Thank you!

**Comment by jtbandes** [comment]
Based on reading https://github.com/foxglove/rosmsg/pull/24 I believe you may need to run `build:gendeps2`.

What are you planning to use the generated `.msg` files for? I don't think this is a common workflow so I wonder if there is a better solution.

**Comment by defunctzombie** [comment]
Related:

I thought that `npx @foxglove/rosmsg gendeps2` would do it but it fails with:

```
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module '../dist/gendeps2'
Require stack:
- /Users/roman/.npm/_npx/f2c186887b20d95e/node_modules/@foxglove/rosmsg/bin/gendeps2
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/Users/roman/.npm/_npx/f2c186887b20d95e/node_modules/@foxglove/rosmsg/bin/gendeps2:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/roman/.npm/_npx/f2c186887b20d95e/node_modules/@foxglove/rosmsg/bin/gendeps2'
  ]
}

Node.js v20.9.0
```

I suspect we don't actually build gendeps2 for the library release which would make sense since it has nothing to do with the features of the library. Maybe we need a new home for it?

**Comment by jtbandes** [comment]
For ROS 2 data, I'd recommend using the built-in ROS 2 bag writer APIs:
- Python example https://mcap.dev/guides/python/ros2#writing
- C++ example https://github.com/ros2/rosbag2/blob/rolling/rosbag2_examples/rosbag2_examples_cpp/src/simple_bag_recorder.cpp

**Comment by huyaoyu** [comment]
Do you mean that even for customized messages, the ways shown in the above python/c++ examples can write messages directly to MCAP? Then how do the schemes of the custom messages get set up for the MCAP writer?

**Comment by jtbandes** [comment]
Yes, rosbag2 handles it internally. See https://github.com/ros2/rosbag2/blob/rolling/docs/message_definition_encoding.md

**Comment by huyaoyu** [comment]
> Yes, rosbag2 handles it internally. See https://github.com/ros2/rosbag2/blob/rolling/docs/message_definition_encoding.md

Thank you for pointing me to the documentation. 

Sorry, I think I didn't mention that I need to do this as an offline pre-processing because I'm working on an iOS App that does not have (good) support for C++/Python. I am trying to write customized data as ROS2 messages and save them into an MCAP file. My current solution is generating these .msg files for my customized messages and using these files in the App.
