### ISSUE TITLE
[QUESTION] - Typescript type generation from ros msg, srv or idl

### ISSUE THREAD

**Issue by MrBlenny** [foxglove/rosmsg#9]
Hello hello,

I'm looking at a way of generating typescript types for messages/services using `.msg`, `.srv` or `.idl` files. I'm not very familiar with ros or rosapi but I'm super impressed & excited by the tooling ya'll at foxglove have been created so I thought I'd raise it here.

What I was thinking was a CLI tool where you configure:
* Output directory, eg) `generated`
* rosbridge_suite rosapi endpoint eg) `ws://localhost:9090`

You would then call a CLI function eg) `ros-ts-type generate -o ./generated -e ws://localhost:9090`
This would:
* Talk to the ros_api and get the interface of all messages and services (I'm not familiar with rosapi)
* Convert each of these msg and srv interfaces to a typescript interface
* Output these interfaces to the `./generated` folder.

Does this workflow make sense? 
What are the challenges in implementing such a thing?
Does foxglove have any other tooling which will help in acheiving this?

**Comment by jhurliman** [comment]
This is definitely possible, but the best way to approach it depends on what you're trying to achieve. Do you want to do binary serialization or deserialization of ROS messages? Or do you just need TypeScript definitions for the structure of your messages but don't need to actually (de)serialize? If you need serialization or deserialization, you'll need to pair this library with <https://github.com/foxglove/rosmsg-serialization>.

You can find an example of TypeScript definition generation in <https://github.com/foxglove/rosmsg-msgs-common/blob/main/src/index.ts>. It would need to be adapted to use either roslibjs + the websocket bridge or <https://github.com/foxglove/ros1> for a direct ROS connection, and query for all data types + message definitions before creating `.d.ts` files.

If you provide more information about your use case I might be able to generalize it into an example tool we could include in one of these repos.

**Comment by MrBlenny** [comment]
Thanks jhurliman. 

That `rosmsg-msgs-common` generation / parse logic looks perfect. I'll have a go making and open-sourcing a CLI.

I was initially thinking about using `roslibjs` and simply annotating the `topic.subscribe` so the de/serialisation is not so critical. What are the benefits of foxglove's ros lib over roslibjs? (I am primaily using ros2)

**Comment by jhurliman** [comment]
The @foxglove/ros1 library connects directly as a ROS 1 node using rostcp. It only supports ROS 1, but a separate ROS 2 library is in progress. It sounds like roslibjs is the right fit for what you need right now. Looking forward to what you create.

**Comment by MrBlenny** [comment]
Yep thanks - was very helpful.
I've made a very basic version here which includes generated types for ros2 foxy. Hoping I'll find the time to add some of the other features soon.
https://github.com/Greenroom-Robotics/ros-typescript-generator

**Comment by amacneil** [comment]
Very cool!

**Comment by defunctzombie** [comment]
@jhurliman Any plans to tackle this? I see you re-opened it some time ago and self-assigned.

**Comment by jhurliman** [comment]
After looking into this further, I'm going to close the ticket as not planned. The main challenge is getting concatenated message definitions. This requires either connecting to rosbridge, implementing the same directory traversing logic from ROS1 ala `gendeps --cat`, and/or implementing ROS2 index parsing ala `mcap convert`. This kind of socket code, filesystem traversal, and index parsing code is currently outside the scope of this repository. It would be better suited for a separate repo similar to the ros-typescript-generator linked in a previous comment.
